### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by LouisCAD** [kotlin-paris/everywhere-website#5]
Browsing to https://everywhere.kotlin.paris/ leads to a `DNS_PROBE_FINISHED_NXDOMAIN` error.

Has the website intentionally been taken offline?

**Comment by SalomonBrys** [comment]
Yes.

**Comment by LouisCAD** [comment]
Why so?

**Comment by SalomonBrys** [comment]
The conference had been long over.
The website can now be accessed at https://kotlin-paris.github.io/everywhere-website/

**Comment by LouisCAD** [comment]
Would have been great to do permanently moved redirects for a while before taking the domain down so search engines learn the new url.

Can you update the links on this repo so we don't land on the dead link?
